In [3]:
# Import the numpy package under the name np
import numpy as np

In [4]:
#Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.26.3
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1704311704800/_build_env/bin/x86_64-conda-linux-gnu-cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.6",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1704311704800/_build_env/bin/x86_64-conda-linux-gnu-c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include directory": 

/home/zeera/miniconda3/envs/data_science_assignment/lib/python3.9/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [5]:
#Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#How to find the memory size of any array
null_vector.size

10

In [7]:
#How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [8]:
#Create a null vector of size 10 but the fifth value which is 1

null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
#Create a vector with values ranging from 10 to 49

ranging_vector = np.arange(10,50)
ranging_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
#Reverse a vector (first element becomes last
flip_vector = np.flip(ranging_vector)
flip_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
#Create a 3x3 matrix with values ranging from 0 to 8
fill_value = np.arange(0,9).reshape(3,3)
fill_value

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#Find indices of non-zero elements from [1,2,0,0,4,0]

indices = [1,2,0,0,4,0]
non_zero = np.nonzero(indices)
non_zero

(array([0, 1, 4]),)

In [13]:
#Create a 3x3 identity matrix

matrix= np.identity(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#Create a 3x3x3 array with random values 
nrandom = np.random.random((3,3,3))
nrandom

array([[[0.67539632, 0.53979489, 0.08422213],
        [0.24431777, 0.3857103 , 0.12267296],
        [0.25265596, 0.10337512, 0.44967648]],

       [[0.62834267, 0.91100745, 0.83814639],
        [0.23602059, 0.36074176, 0.19019454],
        [0.6355224 , 0.22572045, 0.12161   ]],

       [[0.46106272, 0.28493667, 0.66328161],
        [0.22337483, 0.72378965, 0.67017243],
        [0.83552984, 0.93329314, 0.23762326]]])

In [15]:
#Create a 10x10 array with random values and find the minimum and maximum values

random10 = np.random.random((10,10))
random10

array([[0.03237715, 0.62342424, 0.94750757, 0.80638982, 0.44018523,
        0.23268747, 0.02980684, 0.20062598, 0.19052688, 0.96714908],
       [0.64132223, 0.31898445, 0.44524812, 0.73306057, 0.53329038,
        0.6690445 , 0.03036584, 0.20413073, 0.5625872 , 0.9817915 ],
       [0.12089914, 0.04120324, 0.51633665, 0.05523569, 0.91312986,
        0.01240642, 0.96495091, 0.76847544, 0.184419  , 0.23830523],
       [0.75360507, 0.53798808, 0.52432306, 0.19758616, 0.51492554,
        0.84619104, 0.57706584, 0.7438849 , 0.6845931 , 0.45174405],
       [0.08516059, 0.1715005 , 0.22506917, 0.0702172 , 0.52400709,
        0.03948849, 0.25972137, 0.47960267, 0.19438687, 0.61529077],
       [0.44851795, 0.47063102, 0.90577081, 0.12953717, 0.50442217,
        0.0925543 , 0.87580038, 0.86376009, 0.83591175, 0.33241929],
       [0.84650612, 0.42572581, 0.31341602, 0.03818236, 0.3599713 ,
        0.01296514, 0.15728393, 0.59685961, 0.47721137, 0.7445432 ],
       [0.60848252, 0.94293147, 0.4976800

In [16]:
random10.max()

0.9817915001495069

In [17]:
random10.min()

0.012406418617182502

In [18]:
#Create a random vector of size 30 and find the mean value

size30 = np.random.random((30))
print('mean is',size30.mean())
size30

mean is 0.48515340819237995


array([0.2132388 , 0.17584306, 0.8213212 , 0.85201808, 0.87884297,
       0.59282362, 0.77846543, 0.73146104, 0.72503927, 0.78819856,
       0.65527492, 0.60740209, 0.05183963, 0.60851925, 0.10319378,
       0.15217534, 0.70123781, 0.64122028, 0.01087732, 0.33607569,
       0.3909544 , 0.74739905, 0.01458159, 0.08295734, 0.85188536,
       0.46387723, 0.35560753, 0.31944083, 0.02719817, 0.8756326 ])

In [19]:
#Create a 2d array with 1 on the border and 0 inside
border = np.ones((10,10))
border[1:-1,1:-1] = 0
border

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
newborder = np.ones((5,5))
newborder[:, [0, -1]] = 0
newborder[[0, -1], :] = 0
newborder

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
#What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [22]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

narray = np.diag([1,2,3,4],k = -1)
narray

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [23]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [24]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [25]:
#Create a checkerboard 8x8 matrix using the tile function
checkboard = np.tile( np.array([[0,1],[1,0]]), (4,4))
checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [26]:
#Normalize a 5x5 random matrix
normalise = np.random.random((5,5))
normalise = (normalise - np.mean (normalise)) / (np.std (normalise))
normalise

array([[-0.62045756, -0.47457896, -0.62818154,  1.53410732, -1.29850577],
       [-1.08263427,  0.89292569,  1.61917908, -1.011035  , -0.88674578],
       [ 0.37053253, -1.23321928,  1.44940278,  1.51960402,  1.08890021],
       [-0.40876992, -0.93107498,  0.51623489, -0.66055561, -0.46420135],
       [ 0.40450057, -0.73753515,  1.38022772,  0.74747107, -1.08559071]])

In [27]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [28]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

product = np.dot(np.ones((5,3)), np.ones((3,2)))
product

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [29]:
#Given a 1D array, negate all elements which are between 3 and 8, in place

negate = np.arange(11)
negate[(3 < negate) & (negate < 8)] *= -1
negate


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [30]:
# What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [31]:
#What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_864/1958960523.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_864/1958960523.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_864/1958960523.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [ ]:
#How to round away from zero a float array ?
# using the around() fucntion

In [32]:
#How to find common values between two arrays?
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print(np.intersect1d(array1, array2))


[10 40]


In [33]:
#Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)


/tmp/ipykernel_864/2426317694.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [34]:
#How to get the dates of yesterday, today and tomorrow?
# Calculating yesterday's date using NumPy's datetime64 and timedelta64
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)

# Calculating today's date using NumPy's datetime64
today = np.datetime64('today', 'D')
print("Today: ", today)

# Calculating tomorrow's date using NumPy's datetime64 and timedelta64
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Yestraday:  2024-02-08
Today:  2024-02-09
Tomorrow:  2024-02-10


In [35]:
# How to get all the dates corresponding to the month of July 2016?
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [36]:
#How to compute ((A+B)*(-A/2)) in place (without copy)
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [37]:
#Extract the integer part of a random array of positive numbers using 4 different methods
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([-2., -7., -7.,  8., -2., -6., -7.,  0.,  2., -7.])

In [39]:
# Create a 5x5 matrix with row values ranging from 0 to 4
range4 = np.zeros((5,5))
range4 += np.arange(5)
print(range4)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [40]:
 #Consider a generator function that generates 10 integers and use it to build an array 

def generate():
    for x in range(10):
        yield x
generatefunc = np.fromiter(generate(),dtype=float,count=-1)
print(generatefunc)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [41]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded 

zero_one = np.linspace(0,1,11,endpoint=False)[1:]
print(zero_one)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [42]:
#Create a random vector of size 10 and sort it 

rand_vector = np.random.random(10)
rand_vector.sort()
print(rand_vector)

[0.0906245  0.1251725  0.17298345 0.4451831  0.82209904 0.82632438
 0.88634209 0.88685001 0.93533026 0.98361028]


In [43]:
#How to sum a small array faster than np.sum? 

faster_sum = np.arange(10)
np.add.reduce(faster_sum)

45

In [45]:
#Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B)
print(equal)

[0 1 1 1 1]
[0 0 1 0 0]
False


In [46]:
equal = np.array_equal(A,B)
print(equal)

False


In [48]:
 #Make an array immutable (read-only) 

read_only = np.zeros(10)
read_only.flags.writeable = False
read_only[0] = 1

ValueError: assignment destination is read-only