In [2]:
# Import the numpy package under the name np
import numpy as np

In [6]:
#Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.26.3
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1704311704800/_build_env/bin/x86_64-conda-linux-gnu-cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.6",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1704311704800/_build_env/bin/x86_64-conda-linux-gnu-c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include directory": 

/home/zeera/miniconda3/envs/data_science_assignment/lib/python3.9/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [8]:
#Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#How to find the memory size of any array
null_vector.size

10

In [10]:
#How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
#Create a null vector of size 10 but the fifth value which is 1

null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
#Create a vector with values ranging from 10 to 49

ranging_vector = np.arange(10,50)
ranging_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
#Reverse a vector (first element becomes last
flip_vector = np.flip(ranging_vector)
flip_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [24]:
#Create a 3x3 matrix with values ranging from 0 to 8
fill_value = np.arange(0,9).reshape(3,3)
fill_value

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
#Find indices of non-zero elements from [1,2,0,0,4,0]

indices = [1,2,0,0,4,0]
non_zero = np.nonzero(indices)
non_zero

(array([0, 1, 4]),)

In [28]:
#Create a 3x3 identity matrix

matrix= np.identity(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#Create a 3x3x3 array with random values 
nrandom = np.random.random((3,3,3))
nrandom

array([[[0.35410406, 0.94530168, 0.07380031],
        [0.42460835, 0.09117295, 0.5192755 ],
        [0.76331229, 0.97118308, 0.24398747]],

       [[0.29849654, 0.18687582, 0.84196275],
        [0.27440894, 0.98595322, 0.48258125],
        [0.82364036, 0.2148309 , 0.68485194]],

       [[0.62625409, 0.34227167, 0.61210777],
        [0.61567755, 0.68955989, 0.36327387],
        [0.42127889, 0.21376117, 0.2956603 ]]])

In [31]:
#Create a 10x10 array with random values and find the minimum and maximum values

random10 = np.random.random((10,10))
random10

array([[0.40302554, 0.64975345, 0.99164337, 0.68080415, 0.64318296,
        0.60165947, 0.59400119, 0.67115305, 0.30454042, 0.82021758],
       [0.93834616, 0.19679666, 0.46232606, 0.70805244, 0.10175395,
        0.03525752, 0.10637374, 0.25620217, 0.82205959, 0.29035598],
       [0.95700783, 0.33663314, 0.73179821, 0.35568428, 0.21119647,
        0.36237323, 0.35968245, 0.65176121, 0.90684398, 0.14183163],
       [0.50153181, 0.02028822, 0.36212178, 0.00273508, 0.1905624 ,
        0.00926791, 0.73574513, 0.14659855, 0.29357656, 0.70144447],
       [0.40132566, 0.73684684, 0.69596273, 0.78942462, 0.05242023,
        0.3709807 , 0.98185135, 0.75511095, 0.99225761, 0.93370887],
       [0.43939364, 0.48705781, 0.16506391, 0.81357421, 0.97808695,
        0.7711439 , 0.93097638, 0.96417287, 0.69477291, 0.57615321],
       [0.14373315, 0.42426686, 0.71145872, 0.58848863, 0.19691102,
        0.84284786, 0.32929217, 0.90615472, 0.08428656, 0.9397253 ],
       [0.68068984, 0.75761934, 0.8289695

In [32]:
random10.max()

0.9922576089885503

In [33]:
random10.min()

0.0027350775538032

In [34]:
#Create a random vector of size 30 and find the mean value

size30 = np.random.random((30))
print('mean is',size30.mean())
size30

mean is 0.4431476587141342


array([0.06868728, 0.60950071, 0.54876645, 0.39396477, 0.78534539,
       0.61189833, 0.12821294, 0.73346367, 0.91421295, 0.27091314,
       0.78661347, 0.31804874, 0.75740899, 0.01186493, 0.22402646,
       0.17838154, 0.48119586, 0.54792813, 0.17240318, 0.74312168,
       0.18730272, 0.49039143, 0.43714552, 0.64203445, 0.77364499,
       0.54981809, 0.47584591, 0.06812085, 0.25380889, 0.13035828])

In [37]:
#Create a 2d array with 1 on the border and 0 inside
border = np.ones((10,10))
border[1:-1,1:-1] = 0
border

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [44]:
newborder = np.ones((5,5))
newborder[:, [0, -1]] = 0
newborder[[0, -1], :] = 0
newborder

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
#What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [46]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

narray = np.diag([1,2,3,4],k = -1)
narray

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [48]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [49]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [50]:
#Create a checkerboard 8x8 matrix using the tile function
checkboard = np.tile( np.array([[0,1],[1,0]]), (4,4))
checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [52]:
#Normalize a 5x5 random matrix
normalise = np.random.random((5,5))
normalise = (normalise - np.mean (normalise)) / (np.std (normalise))
normalise

array([[-0.22364235,  0.69977669,  0.33044997,  1.32951243, -0.17594801],
       [ 1.19224332, -1.46559842, -0.62186926,  1.29080449,  1.13618193],
       [ 0.6324051 , -1.14734051,  0.72165831, -1.12182614,  0.91271392],
       [ 1.30183302, -0.21158953, -0.04222341,  1.26785196, -0.4122476 ],
       [-2.03206232, -1.17617422, -0.62186541, -0.20229871, -1.36074525]])

In [53]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [56]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

product = np.dot(np.ones((5,3)), np.ones((3,2)))
product

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [57]:
#Given a 1D array, negate all elements which are between 3 and 8, in place

negate = np.arange(11)
negate[(3 < negate) & (negate < 8)] *= -1
negate


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])